### ISSUE TITLE
Pointer mode hover tab not in pointing mode

### ISSUE THREAD

**Issue by le-du6** [freeranger/react-bootstrap-tabs#10]
The pointer hover tab is not in pointing mode (but cursor one). Is this normal ?

**Comment by freeranger** [comment]
The cursor is expected to be in pointer mode when you over over the tab heading if that's what you mean.
If you go to https://freeranger.github.io/react-bootstrap-tabs-demo/ and hover over a tab heading, what do you see?

**Comment by le-du6** [comment]
I see a pointer :)
Sorry for the inconvenience
Thx a lot.
