### ISSUE TITLE
Set Default Tab

### ISSUE THREAD

**Issue by robinprashanth** [freeranger/react-bootstrap-tabs#5]
Is there any way to set default tab? I want the tab 2 to be selected when the component is loaded intially.

**Comment by freeranger** [comment]
If you look at the demo site, I do exactly this in some of the later examples
https://freeranger.github.io/react-bootstrap-tabs-demo/

**Comment by robinprashanth** [comment]
Thanks for the reply.

**Comment by freeranger** [comment]
No problem
