### ISSUE TITLE
React 16 peer dependency

### ISSUE THREAD

**Issue by kunokdev** [freeranger/react-bootstrap-tabs#6]
Could you upgrade peer dependency to support React 16?

**Comment by freeranger** [comment]
Happy to accept a PR provided it doesn't break existing react 15 compatibility

Thanks.

**Comment by kunokdev** [comment]
@freeranger This should do https://github.com/freeranger/react-bootstrap-tabs/pull/7

**Comment by freeranger** [comment]
Merged, thanks
