### ISSUE TITLE
tabs are not showing title/Tab name, what is the issue?

### ISSUE THREAD

**Issue by gowdruNikhil** [freeranger/react-bootstrap-tabs#9]
Code:

import React, {Component} from 'react';
import {connect} from 'react-redux';
import {Tab, Tabs, TabList, TabPanel} from 'react-bootstrap-tabs';

const tabsInstance = (

Tab 1 content
<Tab eventKey={2} title="Tab 2">
Tab 2 content
</Tab>

<Tab eventKey={3} title="Tab 3">Tab 3 content</Tab>
);
class ProfileTab extends Component {
constructor(props){
super(props);

}
render(){
return (

{tabsInstance}

);
}
}

export default ProfileTab;

**Comment by freeranger** [comment]
Please add a minimal full project demonstrating the problem - a code sample that is not formatted as code does not help to reproduce.
Have you looked at the demo site linked to from this repo?  It shows the tabs fully working and you can look at the code behind it too to see how to create the tabs
https://freeranger.github.io/react-bootstrap-tabs-demo/
https://github.com/freeranger/react-bootstrap-tabs-demo

**Comment by freeranger** [comment]
Closing due to no response
